#!/bin/sh
#
# Sign a SSL certificate for a specific domain name. 
#
#   sign-certificate domainname CSR-file
#

# -- initialize CA ------------------------------------------------------------

HERE=$(cd `dirname $0` && pwd)
. $HERE/init-ca

# -- generate certificate -----------------------------------------------------

certname=$1; shift
csr_file=$1; shift

if [ -z "$csr_file" ]; then
  echo "Usage: $0 <subdomain> <csr-file>" >&2
  exit 1
fi

if ! [ -f "$csr_file" ]; then
  echo "Missing file $csr_file." >&2
  exit 1
fi

# [todo] check certname is valid
#
# [todo] check that certificate does not exist yet. Should we use ssl.conf's
# unique_subject setting?.

openssl ca -batch \
  -config $HERE/ssl.conf \
  -policy policy_anything \
  -out "$OPENSSL_DIR/certs/$certname.pem" \
  -infiles "$csr_file"
