#!/usr/bin/env ruby
#
# Start a console that initializes the gem
#
require "irb"
require "rubygems"

begin
  require 'wirble'
  Wirble.init
  Wirble.colorize
rescue LoadError
  STDERR.puts "To enable colorized and tab completed run 'gem install wirble'"
end

Dir.chdir File.join(File.dirname(__FILE__), "..")

require_relative "../config/environment"

if RACK_ENV == "development"
  require "etest-unit"
end
$: << "app/model"

IRB.start
