#!/bin/bash
usage() {
  echo "setup_account port,port,port rule-name"
  exit 1
}

set -e

PORTS=$1
RULE_NAME=$2
iptables="sudo iptables"

[ "$RULE_NAME" ] || usage
[ "$PORTS" ] || usage

$iptables -N ${RULE_NAME} || true

$iptables -C INPUT -p tcp -j $RULE_NAME -m multiport --dports $PORTS ||
$iptables -A INPUT -p tcp -j $RULE_NAME -m multiport --dports $PORTS

