#!/bin/bash

# fix environment

PATH=$PATH:/usr/local/bin
USER=`whoami`
if [ -z "$HOME" ]; then
  HOME=$(eval echo ~$USER)
fi

# load rvm if present

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  source "$HOME/.rvm/scripts/rvm" 
fi

# change into directoy

cd $(dirname $0)/..

if [[ -e ".rvmrc" ]]; then
  source ".rvmrc"
fi

# start process.
# exec bundle exec rackup -p 5000
#set -xve
#bundle "$@*"
cmd=$(eval echo $*)
exec bundle $cmd
echo "could not start bundle $cmd" >2 
