#!/usr/bin/env ruby
# ./script/issue This will be the issue title @radiospiel \#high

require "shellwords"


message = ARGV.join(" ")

users, labels = [], []
message.gsub!(/\s([@#])([a-zA-Z0-9]*)\b/) do
  ($1 == "@" ? users : labels) << $2
  " "
end
message.gsub! /\s+/, " "

if message == ""
  STDERR.puts "Missing issue title"
  exit 1
end

cmd = [ "ghi", "open", "-m", message.shellescape ]
cmd += [ "-u", users.join(",") ] unless users.empty?
cmd += [ "-L", labels.join(",") ] unless labels.empty?
cmd = cmd.join(" ")

begin
  puts cmd
  puts "Continue? (return or ^C)"
  STDIN.gets
  system cmd
rescue Interrupt
  exit 1
end
