#!/bin/sh
#
# Generate a SSL certificate for a specific domain name. 
#
#   mk-certificate domainname
#

# openssl settings
VALIDITY=7300
ROOT=$(cd `dirname $0`/.. && pwd)
HERE=$(cd `dirname $0` && pwd)

export OPENSSL_DIR=$ROOT/var/openssl

. $HERE/ca-settings

# -- generate CA --------------------------------------------------------------

if ! [ -e $OPENSSL_DIR/index.txt ]; then
  
  # -- create CA directory structure ------------------------------------------

  mkdir -p -m 0755 $OPENSSL_DIR/private \
    $OPENSSL_DIR/certs \
    $OPENSSL_DIR/csr \
    $OPENSSL_DIR/newcerts \
    $OPENSSL_DIR/crl \
    $OPENSSL_DIR/root
  
  touch $OPENSSL_DIR/index.txt
  echo '01' > $OPENSSL_DIR/serial     

  # -- create CA root private key ---------------------------------------------
  openssl genrsa -out $OPENSSL_DIR/root/private_key.pem 2048
  
  # -- create self signed root certificate ------------------------------------
  openssl req -new \
    -subj "/C=$CA_COUNTRY/ST=$CA_STATE/L=$CA_CITY/CN=pipe2me-root" \
    -out $OPENSSL_DIR/root/certificate.pem \
    -key $OPENSSL_DIR/root/private_key.pem -x509 \
    -days 7300

  # -- Create an initial empty certificate revocation list (CRL)

  openssl ca -config $HERE/ssl.conf \
    -gencrl \
    -keyfile $OPENSSL_DIR/root/private_key.pem \
    -cert $OPENSSL_DIR/root/certificate.pem \
    -out $OPENSSL_DIR/crl/crl.pem

fi

# -- generate certificate -----------------------------------------------------

certname=$1
if [ -z "$certname" ]; then
  echo "Usage: $0 <subdomain>"
  exit 1
fi

# [todo] check certname is valid
#
# [todo] check that certificate does not exist yet. Should we use ssl.conf's
# unique_subject setting?.

mkdir -p $OPENSSL_DIR/private/
mkdir -p $OPENSSL_DIR/csr/
mkdir -p $OPENSSL_DIR/certs/

#create certificate/private key
openssl req \
  -config $HERE/ssl.conf \
  -new \
  -nodes \
  -keyout "$OPENSSL_DIR/private/$certname.pem" \
  -out "$OPENSSL_DIR/csr/$certname.csr" \
  -days $VALIDITY \
  -subj "/C=$CA_COUNTRY/ST=$CA_STATE/L=$CA_CITY/O=$CA_ORGANIZATION/OU=$CA_ORG_UNIT/CN=$certname"

openssl ca -batch \
  -config $HERE/ssl.conf \
  -policy policy_anything \
  -out "$OPENSSL_DIR/certs/$certname.pem" \
  -infiles "$OPENSSL_DIR/csr/$certname.csr"
