source "https://rubygems.org"

gem "foreman"

# -- web server framework -----------------------------------------------------

group :production do
  gem "thin"
end

gem "rack"
gem "rack_csrf"

gem "sinatra"
gem "sinatra-contrib"

# -- models -------------------------------------------------------------------

gem "sinatra-activerecord"
gem "sqlite3"
gem "rake"

group :development do
  gem "wirble"
end

group :development do
  gem "etest-unit"
end
